# Application Name and Server Settings
spring.application.name=server
server.port=8010

# Spring Data JPA (MySQL)
spring.datasource.url=jdbc:mysql://localhost:3306/hrportal?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update  
spring.jpa.show-sql=true  
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JWT Settings

jwt.expiration=3600  
jwt.header=Authorization  
jwt.prefix=Bearer  

spring.jackson.serialization.indent-output=true


# CORS Configuration
# You can specify allowed origins, methods, etc., for cross-origin requests (Frontend to Backend communication)
# Example configuration:
# spring.webflux.cors.allowed-origins=http://localhost:3000
